#!/usr/bin/php
<?php

namespace {
    error_reporting(E_ALL | E_STRICT);
    ini_set('display_errors', true);

    require_once 'ztest/ztest.php';
    require_once __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'phuby.php';
}

namespace Phuby {
    $support_files = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator(__DIR__.DS.'support'), \RecursiveIteratorIterator::SELF_FIRST);
    foreach ($support_files as $file) require $file;

    $reporter = new \ztest\ConsoleReporter;
    $reporter->enable_color();

    $suite = new \ztest\TestSuite('Phuby unit tests');
    $suite->require_all(__DIR__.DS.'unit');
    $suite->auto_fill();
    $suite->run($reporter);
}